// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ArtifactController from "./artifact_controller"
application.register("artifact", ArtifactController)

import ArtifactSelectController from "./artifact_select_controller"
application.register("artifact-select", ArtifactSelectController)

import AssistantUserChatController from "./assistant_user_chat_controller"
application.register("assistant-user-chat", AssistantUserChatController)

import AutoExpandController from "./auto_expand_controller"
application.register("auto-expand", AutoExpandController)

import ChatScrollController from "./chat_scroll_controller"
application.register("chat-scroll", ChatScrollController)

import MessageFormController from "./message_form_controller"
application.register("message-form", MessageFormController)

import ProjectMenuController from "./project_menu_controller"
application.register("project-menu", ProjectMenuController)

import SvgZoomController from "./svg_zoom_controller"
application.register("svg-zoom", SvgZoomController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)
